# Explicit SDK only: never mix PATH/MSYS headers with an unrelated DLL set.
set(FFMPEG_ROOT "" CACHE PATH "Unpacked Windows x64 FFmpeg shared SDK")
if(NOT IS_DIRECTORY "${FFMPEG_ROOT}/include")
  message(FATAL_ERROR "Set FFMPEG_ROOT to a shared FFmpeg SDK (see setup-ffmpeg.ps1).")
endif()
file(READ "${FFMPEG_ROOT}/include/libavutil/ffversion.h" ffmpeg_version_header)
string(REGEX MATCH "FFMPEG_VERSION \"([^\"]+)\"" _ "${ffmpeg_version_header}")
set(FFmpeg_VERSION "${CMAKE_MATCH_1}")
set(FFmpeg_RUNTIME_FILES "")
foreach(component avformat avcodec avutil swresample)
  set(library "${FFMPEG_ROOT}/lib/${component}.lib")
  file(GLOB runtime "${FFMPEG_ROOT}/bin/${component}-*.dll")
  list(LENGTH runtime count)
  if(NOT EXISTS "${library}" OR NOT count EQUAL 1)
    message(FATAL_ERROR "FFmpeg SDK requires ${component}.lib and exactly one matching DLL")
  endif()
  add_library(FFmpeg::${component} SHARED IMPORTED)
  set_target_properties(FFmpeg::${component} PROPERTIES
    IMPORTED_IMPLIB "${library}" IMPORTED_LOCATION "${runtime}"
    INTERFACE_INCLUDE_DIRECTORIES "${FFMPEG_ROOT}/include")
  list(APPEND FFmpeg_RUNTIME_FILES "${runtime}")
endforeach()
set(FFmpeg_FOUND TRUE)
message(STATUS "FFmpeg SDK: ${FFmpeg_VERSION} (${FFMPEG_ROOT})")
